use core::fmt;
use std::collections::BTreeSet;

use candid::{CandidType, Principal};
use serde::{Deserialize, Serialize};

use crate::types::series::SocialLimits;

/// A unique, opaque identifier for an Engine.
///
/// Generated by the registry canister as `"eng_{counter}"`.
#[derive(
    CandidType, Serialize, Deserialize, Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
pub struct EngineId(String);

impl From<String> for EngineId {
    fn from(value: String) -> Self {
        Self(value)
    }
}

impl EngineId {
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for EngineId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

/// Roles that can be granted to principals within an Engine.
///
/// This is a fixed enum extended over time at the protocol level.
/// Engines declare which subset of roles they are allowed to grant
/// via [`Engine::allowed_roles`].
#[derive(
    CandidType, Serialize, Deserialize, Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
pub enum EngineRole {
    /// Can create series via `add_series` and fork series via `fork_series`.
    Creator,
    /// Can register oracles and manage their metadata and principals.
    OracleAdmin,
}

/// An audit record of a role grant within an Engine.
#[derive(CandidType, Serialize, Deserialize, Clone, Debug)]
pub struct RoleGrant {
    /// The principal that received the role.
    pub principal: Principal,
    /// The granted role.
    pub role: EngineRole,
    /// The principal that performed the grant.
    pub granted_by: Principal,
    /// Timestamp of the grant in nanoseconds since UNIX epoch.
    pub granted_at_ns: u64,
}

/// A multi-tenant organizational entity for dApps using the clearing layer.
///
/// Engines allow dApps to autonomously manage their own creators, oracle
/// admins, and other roles without being canister controllers. Each Engine
/// has a set of admins who can grant roles to principals, subject to the
/// `allowed_roles` constraint set by the canister controllers at registration.
#[derive(CandidType, Serialize, Deserialize, Clone, Debug)]
pub struct Engine {
    /// Unique identifier assigned at creation.
    pub engine_id: EngineId,
    /// A human-readable name for the Engine (e.g., "Vici App").
    pub name: String,
    /// An optional description of the Engine's purpose.
    pub description: Option<String>,
    /// An optional icon/avatar URL for the Engine.
    pub icon_url: Option<String>,
    /// The principal that registered this Engine (a canister controller).
    pub creator: Principal,
    /// Principals with administrative privileges on this Engine.
    /// Admins can grant/revoke roles and manage other admins.
    /// The creator is implicitly an admin.
    pub admins: BTreeSet<Principal>,
    /// The subset of [`EngineRole`] variants this Engine is allowed to grant.
    /// Set by the canister controller at registration time. Admins cannot
    /// grant roles outside this set.
    pub allowed_roles: BTreeSet<EngineRole>,
    /// Audit trail of all active role grants.
    pub role_grants: Vec<RoleGrant>,
    /// Optional per-engine override for social market rate limits.
    pub social_limits: Option<SocialLimits>,
    /// Timestamp of engine creation in nanoseconds since UNIX epoch.
    pub created_at_ns: u64,
    /// Timestamp of the last mutation in nanoseconds since UNIX epoch.
    pub updated_at_ns: u64,
    /// The principal that performed the last mutation.
    pub updated_by: Principal,
}

/// Input parameters for registering a new Engine.
///
/// Only canister controllers may call `register_engine`.
#[derive(CandidType, Serialize, Deserialize, Clone, Debug)]
pub struct RegisterEngineParams {
    /// A human-readable name for the Engine.
    pub name: String,
    /// An optional description.
    pub description: Option<String>,
    /// An optional icon URL.
    pub icon_url: Option<String>,
    /// Initial admin principals. The caller is always added as an admin.
    pub admins: Vec<Principal>,
    /// The set of roles this Engine is allowed to grant.
    pub allowed_roles: Vec<EngineRole>,
}

/// Input parameters for updating an existing Engine's metadata.
///
/// Only Engine admins or canister controllers may call `update_engine`.
#[derive(CandidType, Serialize, Deserialize, Clone, Debug)]
pub struct UpdateEngineParams {
    /// The Engine to update.
    pub engine_id: EngineId,
    /// New name, or `None` to keep the current name.
    pub name: Option<String>,
    /// New description: `None` = keep, `Some(None)` = clear, `Some(Some(..))` = set.
    pub description: Option<Option<String>>,
    /// New icon URL: `None` = keep, `Some(None)` = clear, `Some(Some(..))` = set.
    pub icon_url: Option<Option<String>>,
}

/// Input parameters for updating the allowed roles of an Engine.
///
/// Only canister controllers may call this.
#[derive(CandidType, Serialize, Deserialize, Clone, Debug)]
pub struct UpdateEngineAllowedRolesParams {
    /// The Engine to update.
    pub engine_id: EngineId,
    /// The new set of allowed roles. Replaces the existing set entirely.
    pub allowed_roles: Vec<EngineRole>,
}

/// Input parameters for granting a role within an Engine.
///
/// Only Engine admins or canister controllers may grant roles.
#[derive(CandidType, Serialize, Deserialize, Clone, Debug)]
pub struct GrantEngineRoleParams {
    /// The Engine in which to grant the role.
    pub engine_id: EngineId,
    /// The principal receiving the role.
    pub principal: Principal,
    /// The role to grant.
    pub role: EngineRole,
}

/// Input parameters for revoking a role within an Engine.
///
/// Only Engine admins or canister controllers may revoke roles.
#[derive(CandidType, Serialize, Deserialize, Clone, Debug)]
pub struct RevokeEngineRoleParams {
    /// The Engine in which to revoke the role.
    pub engine_id: EngineId,
    /// The principal losing the role.
    pub principal: Principal,
    /// The role to revoke.
    pub role: EngineRole,
}

/// Input parameters for managing Engine admins (adding or removing).
#[derive(CandidType, Serialize, Deserialize, Clone, Debug)]
pub struct UpdateEngineAdminsParams {
    /// The Engine to modify.
    pub engine_id: EngineId,
    /// Principals to add or remove as admins.
    pub principals: Vec<Principal>,
}

/// Errors that can occur during Engine-related operations.
#[derive(CandidType, Serialize, Deserialize, Clone, Debug)]
pub enum EngineError {
    /// The specified Engine ID does not exist.
    EngineNotFound,
    /// The caller is not authorized for this operation.
    Unauthorized,
    /// The Engine name exceeds the maximum allowed length.
    NameTooLong,
    /// An Engine with this name already exists.
    EngineAlreadyExists,
    /// The requested role is not in the Engine's `allowed_roles`.
    RoleNotAllowed,
    /// The principal already has this role in this Engine.
    RoleAlreadyGranted,
    /// The principal does not have this role in this Engine.
    RoleNotGranted,
    /// Cannot remove the Engine creator as an admin.
    CannotRemoveCreator,
}

/// The result of a `register_engine` operation.
#[derive(CandidType, Serialize, Deserialize, Clone, Debug)]
pub enum RegisterEngineResult {
    Ok(EngineId),
    Err(EngineError),
}

impl From<Result<EngineId, EngineError>> for RegisterEngineResult {
    fn from(value: Result<EngineId, EngineError>) -> Self {
        match value {
            Ok(v) => RegisterEngineResult::Ok(v),
            Err(e) => RegisterEngineResult::Err(e),
        }
    }
}

/// The result of an Engine mutation operation.
#[derive(CandidType, Serialize, Deserialize, Clone, Debug)]
pub enum EngineResult {
    Ok,
    Err(EngineError),
}

impl From<Result<(), EngineError>> for EngineResult {
    fn from(value: Result<(), EngineError>) -> Self {
        match value {
            Ok(()) => EngineResult::Ok,
            Err(e) => EngineResult::Err(e),
        }
    }
}
