//! Types for the **closed circles** feature: trading groups and access policies.
//!
//! A "closed circle" restricts who may trade a particular derivative series.
//! Groups hold a set of member principals; series reference groups through
//! [`TradingAccess`] policies. The clearing canister enforces these policies
//! at order-submission time by querying the registry.

use std::collections::BTreeSet;

use candid::{CandidType, Principal};
use serde::{Deserialize, Serialize};

/// A unique, opaque identifier for a trading group.
///
/// Generated by the registry canister as `"grp_{counter}"`.
/// Two groups on different registries may collide; within a single
/// registry the ID is guaranteed unique and monotonically increasing.
#[derive(
    CandidType, Serialize, Deserialize, Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
pub struct GroupId(String);

impl From<String> for GroupId {
    fn from(value: String) -> Self {
        Self(value)
    }
}

impl GroupId {
    /// Returns the inner string representation of the group ID.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// A trading group (closed circle).
///
/// Groups are the building blocks of restricted trading access.
/// A user creates a group, invites members by principal, and an admin
/// can then assign one or more groups to a series via [`TradingAccess::Restricted`].
///
/// Only group members (and canister controllers) may trade on series
/// that are restricted to that group.
#[derive(CandidType, Serialize, Deserialize, Clone, Debug)]
pub struct Group {
    /// The unique identifier assigned at creation.
    pub group_id: GroupId,
    /// A human-readable display name for the group (max 128 chars).
    pub name: String,
    /// The principal that created this group. Has permission to
    /// add/remove members and delete the group.
    pub creator: Principal,
    /// The set of principals who are members of this group.
    /// Members are authorized to trade on any series restricted to this group.
    pub members: BTreeSet<Principal>,
    /// Timestamp of group creation in nanoseconds since UNIX epoch.
    pub created_at_ns: u64,
}

/// A single trading access policy attached to a derivative series.
///
/// A [`Series`](super::series::Series) holds a `Vec<TradingAccess>`.
/// Authorization is evaluated as a logical **OR** across all policies:
/// if *any* policy in the list grants access to the caller, the caller
/// may trade.
///
/// # Invariant
///
/// The `trading_access` vector on a [`Series`](super::series::Series) **must
/// never be empty**. Every series must carry at least one policy. The default
/// is `[Open]`. This invariant is enforced at the API level (`add_series`,
/// `update_trading_access`) and at the deserialization level (`serde(default)`
/// fills `[Open]` for legacy series that lack the field).
///
/// # Combining policies
///
/// A series may carry multiple policies simultaneously. For example:
/// - `[Open]` — open to everyone (default).
/// - `[Restricted { groups: [g1, g2] }]` — only members of g1 or g2.
/// - `[Open, Restricted { groups: [g1] }]` — open to everyone *and* additionally tagged as
///   belonging to g1 (useful for discovery/UI filtering).
///
/// # Extensibility
///
/// New variants (e.g. `TokenGated`, `ReputationBased`) can be added in
/// the future without breaking existing policies or on-chain state.
#[derive(CandidType, Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum TradingAccess {
    /// Unrestricted: any authenticated (non-anonymous) caller can trade.
    Open,
    /// Restricted to members of the specified groups.
    /// The caller is authorized if they belong to **at least one** of the
    /// listed groups.
    Restricted {
        /// The group IDs whose members are allowed to trade.
        groups: Vec<GroupId>,
    },
}

/// Input parameters for creating a new trading group.
///
/// The caller's principal is automatically recorded as the group creator
/// and added as the first member.
#[derive(CandidType, Serialize, Deserialize, Clone, Debug)]
pub struct CreateGroupParams {
    /// A human-readable name for the group. Must not exceed 128 characters.
    pub name: String,
}

/// Input parameters for adding or removing members from a group.
///
/// Used by both `add_group_members` and `remove_group_members`.
/// Only the group creator or a canister controller may call these.
#[derive(CandidType, Serialize, Deserialize, Clone, Debug)]
pub struct UpdateGroupMembersParams {
    /// The group to modify.
    pub group_id: GroupId,
    /// The principals to add or remove.
    pub principals: Vec<Principal>,
}

/// Input parameters for replacing the trading access policies on a series.
///
/// Only canister controllers (admins) may call `update_trading_access`.
/// The entire policy list is replaced atomically.
#[derive(CandidType, Serialize, Deserialize, Clone, Debug)]
pub struct UpdateTradingAccessParams {
    /// The series whose trading access policies will be replaced.
    pub series_id: super::series::SeriesId,
    /// The new set of trading access policies. **Must not be empty.**
    /// Pass `[Open]` to make the series unrestricted.
    pub trading_access: Vec<TradingAccess>,
}

/// Errors that can occur during group-related operations.
#[derive(CandidType, Serialize, Deserialize, Clone, Debug)]
pub enum GroupError {
    /// The specified group ID does not exist in the registry.
    GroupNotFound,
    /// The caller does not have permission for this operation.
    /// Typically means the caller is neither the group creator nor a controller.
    Unauthorized,
    /// The provided group name exceeds the maximum allowed length (128 chars).
    NameTooLong,
    /// A group with this name already exists for this creator.
    GroupAlreadyExists,
    /// The referenced series ID does not exist in the registry.
    /// Returned by `update_trading_access` when the target series is missing.
    SeriesNotFound,
    /// The provided `trading_access` list is empty.
    /// Every series must have at least one policy (e.g. `[Open]`).
    EmptyTradingAccess,
}

/// The result of a [`create_group`] operation.
///
/// Returns the newly assigned [`GroupId`] on success.
#[derive(CandidType, Serialize, Deserialize, Clone, Debug)]
pub enum CreateGroupResult {
    /// The group was created successfully.
    Ok(GroupId),
    /// The group creation failed.
    Err(GroupError),
}

impl From<Result<GroupId, GroupError>> for CreateGroupResult {
    fn from(value: Result<GroupId, GroupError>) -> Self {
        match value {
            Ok(v) => CreateGroupResult::Ok(v),
            Err(e) => CreateGroupResult::Err(e),
        }
    }
}

/// The result of a group mutation operation (add/remove members, delete, update access).
///
/// Returns `true` on success.
#[derive(CandidType, Serialize, Deserialize, Clone, Debug)]
pub enum GroupResult {
    /// The operation succeeded.
    Ok(bool),
    /// The operation failed.
    Err(GroupError),
}

impl From<Result<bool, GroupError>> for GroupResult {
    fn from(value: Result<bool, GroupError>) -> Self {
        match value {
            Ok(v) => GroupResult::Ok(v),
            Err(e) => GroupResult::Err(e),
        }
    }
}
