[package]
name = "pricer"
version = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-cdk-timers = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shared = { workspace = true }

[dev-dependencies]
pocket-ic = { workspace = true }

[[test]]
name = "it"
path = "tests/it.rs"

[lints]
workspace = true
